[[CSDP]]
arch = "i686"
git-tree-sha1 = "60217df4870db2690707383db94e431b56f2aa8c"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "df0608d84f7b4c511ef002271f0f6a9481a81da3e3c751d36392d6fc89540cf2"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+4/CSDP.v6.2.0.i686-linux-musl.tar.gz"
[[CSDP]]
arch = "aarch64"
git-tree-sha1 = "5a029b59cdc1b25e5dda541305b6479a50ce0cb6"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "1e0c1e5c89e6b70538ff9b4e705bda3d267721ae4d58ee600152bc5f6101bf46"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+4/CSDP.v6.2.0.aarch64-linux-musl.tar.gz"
[[CSDP]]
arch = "i686"
git-tree-sha1 = "1e4be7db9e47c5553ccc72f484b6ab171edfcfd5"
os = "windows"

    [[CSDP.download]]
    sha256 = "33f83f94bcec13087f9fa9276345ec296722b14b6a28c3790bb494e419bf41ea"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+4/CSDP.v6.2.0.i686-w64-mingw32.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "ccb66aab0eb195669ed7fe687debc8fdee1a30c7"
os = "windows"

    [[CSDP.download]]
    sha256 = "181520ca04efb32323a369ecee7d067937d9a59d5f45ed4b78d3669f8a52769d"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+4/CSDP.v6.2.0.x86_64-w64-mingw32.tar.gz"
[[CSDP]]
arch = "armv7l"
git-tree-sha1 = "02668327582584bc8d393f34b53a14771974244b"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "88532fc19eb7a33b72bad0b7e01d61b1bd29b6069b4a883d468d6e12f00cf711"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+4/CSDP.v6.2.0.armv7l-linux-gnueabihf.tar.gz"
[[CSDP]]
arch = "armv7l"
git-tree-sha1 = "7b587ea6db76ba63e07e268d92adaf13afbe5ae5"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "f1dd8bba6a91b4c94394ad421487b99249c8abd592dfbb2256d0dee704ea2a82"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+4/CSDP.v6.2.0.armv7l-linux-musleabihf.tar.gz"
[[CSDP]]
arch = "i686"
git-tree-sha1 = "d8373f6b6243f137b04de2bbc1905a30853e9562"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "80e2a2b2263ca378efb23cd565814bd66f5e120cdb955e9bdf548ab32b43b75d"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+4/CSDP.v6.2.0.i686-linux-gnu.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "091c57a6d7c6a37eb5385ced8ad5e16c776bafc7"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "7ddaafbe0079f6852b60c3479bbed050b367931da3c231ba26ef20c2b71c698f"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+4/CSDP.v6.2.0.x86_64-linux-gnu.tar.gz"
[[CSDP]]
arch = "powerpc64le"
git-tree-sha1 = "354d6b6df5166b2e3073ec548a341835040507a9"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "461214a00369395ccd544ec40e7c89d787fcc2a869aeb73a832f79ff06c16b97"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+4/CSDP.v6.2.0.powerpc64le-linux-gnu.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "c19240d500b3eeab773a3d43b08a301c5b3553db"
os = "macos"

    [[CSDP.download]]
    sha256 = "af4cbf6d324b32f26e3700d50ed2950eebbd3bdc6cc13eae8c1d15ba25c70de6"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+4/CSDP.v6.2.0.x86_64-apple-darwin14.tar.gz"
[[CSDP]]
arch = "aarch64"
git-tree-sha1 = "b7b9dfd730408b33ae05babb4498584a97240624"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "446a2d5c60a9270a345d2aab12093c76accab967c175ff96de7f684e48c2f482"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+4/CSDP.v6.2.0.aarch64-linux-gnu.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "634e1c01fb37d6902fed19ccb7f82b239f0d5e20"
os = "freebsd"

    [[CSDP.download]]
    sha256 = "d7affbc5d639bff71fce4848d77d368dbca49dd8125cf849a416c4c059668201"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+4/CSDP.v6.2.0.x86_64-unknown-freebsd11.1.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "58936c1bd2146c77d11a4ae3c3c99bcfbfbdce7d"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "337e68f51132e080d8bb5cdf79197326df9637ede69ed9258c67626a99edc7b5"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+4/CSDP.v6.2.0.x86_64-linux-musl.tar.gz"
