[[CSDP]]
arch = "i686"
git-tree-sha1 = "799a814c576c21de1f042e7d4e5826d33584e19b"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "54a8b37a5694bd0873683387b2d3b627be9f654fe8ce3a2498f92672c5d4074c"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+2/CSDP.v6.2.0.i686-linux-musl.tar.gz"
[[CSDP]]
arch = "aarch64"
git-tree-sha1 = "846dfb2b232acdcade1866d2b220391f9f272fc5"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "bd41371badecc76ef087e63c1ddf38dce7b3ed1b7fd8f8ca5ee521c7624f16bf"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+2/CSDP.v6.2.0.aarch64-linux-musl.tar.gz"
[[CSDP]]
arch = "i686"
git-tree-sha1 = "59e6186a0be4cd2d8876eb8079064236134fcee5"
os = "windows"

    [[CSDP.download]]
    sha256 = "747933efd24bba9a62ccc03050ff4bd08b40af3a77912092ed68cae6783c384e"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+2/CSDP.v6.2.0.i686-w64-mingw32.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "c9d8c0bb0ee88271fe62d3543f013359b0cee8e2"
os = "windows"

    [[CSDP.download]]
    sha256 = "b7947162d112ef6bc2498e8f97b47f9dd921974b77afb8161df34d78949ea163"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+2/CSDP.v6.2.0.x86_64-w64-mingw32.tar.gz"
[[CSDP]]
arch = "armv7l"
git-tree-sha1 = "35f45a5fefcb6f425167df2d711f45b115a26ba6"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "dec63195b2859033b105014b297043dae3e64bfff90880e06e31f40ae65e7aac"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+2/CSDP.v6.2.0.armv7l-linux-gnueabihf.tar.gz"
[[CSDP]]
arch = "armv7l"
git-tree-sha1 = "83a25680a08212ca8ecb081ca06b4ece35131832"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "a30b84caa2195bac7d01b1886818a902f9ec455cce4eb122c0e3b237c7f498ed"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+2/CSDP.v6.2.0.armv7l-linux-musleabihf.tar.gz"
[[CSDP]]
arch = "i686"
git-tree-sha1 = "54ee4fb4b7e08fd07cbbc29be212db3fa523c7f8"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "fb3508bf2043cab55225f95cf3cf06f892cf146884b6e78cd7e8c88a008043bf"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+2/CSDP.v6.2.0.i686-linux-gnu.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "d6f35af56dc0d467a30c65ba7ed98e862f18800e"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "034b11638befbb070af8b0051c152f65458dd0cbee89317d15e3f2c9dc1ee629"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+2/CSDP.v6.2.0.x86_64-linux-gnu.tar.gz"
[[CSDP]]
arch = "powerpc64le"
git-tree-sha1 = "84deaf7e233d4c1e3ad202637619ec94330f0add"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "22f3b94f68a55467c5fa0b6a18c7ae7e968fbef7c4cdda2f89a48c1ae78e79f7"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+2/CSDP.v6.2.0.powerpc64le-linux-gnu.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "973df7d90beed39003c79508c9208a414734c56d"
os = "macos"

    [[CSDP.download]]
    sha256 = "d1de7f68cf7c28c3150701ef5ee750d0aa118730905a0e267140adfe985c0163"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+2/CSDP.v6.2.0.x86_64-apple-darwin14.tar.gz"
[[CSDP]]
arch = "aarch64"
git-tree-sha1 = "9bf1862a0b65e09c30b38e9ea37d231796fb479a"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "4a366adbd09ee0b035399ee7ca6847455cf1960c9be6c03de6b70a7eb3e7050e"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+2/CSDP.v6.2.0.aarch64-linux-gnu.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "390f17ec9cb86ece40e77900b92796a434abbfc4"
os = "freebsd"

    [[CSDP.download]]
    sha256 = "79405835ca8ef667b06dc0ef08a7781e2b3cb1722a2733eacf755d8b5a87a348"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+2/CSDP.v6.2.0.x86_64-unknown-freebsd11.1.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "8173a6f91cd62a8902009fe7fddb9db119d3e493"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "6e826f6b5fc55da20eeb7a94f0f03841d873e9a435b48ea770c88e769ec031d9"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+2/CSDP.v6.2.0.x86_64-linux-musl.tar.gz"
