[[CSDP]]
arch = "i686"
git-tree-sha1 = "4927bdd9b0b89eb30e8342c88c83e6247b972a6e"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "773985b2e56e1429da1ad335e23338c76455c3247ad43b6e0634be4f1c87f44c"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+6/CSDP.v6.2.0.i686-linux-musl.tar.gz"
[[CSDP]]
arch = "aarch64"
git-tree-sha1 = "b79c385582cc8f9c2d9b09d024633b7826739d05"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "725331f50ffe150f38e7016c62cba6f6cd26b17877334d3d52bf9f388fb6ca91"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+6/CSDP.v6.2.0.aarch64-linux-musl.tar.gz"
[[CSDP]]
arch = "i686"
git-tree-sha1 = "75700493456fbe6fc95446edad97fa4ad3f2fb34"
os = "windows"

    [[CSDP.download]]
    sha256 = "de79aaed2766b7c5eaaf519d99565e8dbe930a64dadbe8d68652be81d4d34049"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+6/CSDP.v6.2.0.i686-w64-mingw32.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "68555af93238c4c19ca2f77123694a80650bb471"
os = "windows"

    [[CSDP.download]]
    sha256 = "dbfa697ecc7db48309484da741191d3eba00a6a917c23bc6fa54c91b2dd35910"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+6/CSDP.v6.2.0.x86_64-w64-mingw32.tar.gz"
[[CSDP]]
arch = "armv7l"
git-tree-sha1 = "aa649c3b9614855e60bb96bc7965d3126dfc517a"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "6d241b22a6fc4a48c9df4fe06daa01993d57e3c7d3427da25b62946dfb1b8bf6"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+6/CSDP.v6.2.0.armv7l-linux-gnueabihf.tar.gz"
[[CSDP]]
arch = "armv7l"
git-tree-sha1 = "e3d130056577c15cae614c4beba8790e82c73431"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "9aecd5eb4f1bfac4506218c8be8f1a7ae13544ec11db164d928663b8daeb58ba"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+6/CSDP.v6.2.0.armv7l-linux-musleabihf.tar.gz"
[[CSDP]]
arch = "i686"
git-tree-sha1 = "95a258cbe621e5ddb002965abe46019b7976abcc"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "e27b6bf971f01f4e480a278bed8c208b6168bcf2e772d3de58f1f5782bdf688c"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+6/CSDP.v6.2.0.i686-linux-gnu.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "1b8bc8c9cd718f5c48e87fd833b2d3781473ba79"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "003215e8bad55299528c0085827a91cf9b72ed0493cebe517116aa3821fabaf7"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+6/CSDP.v6.2.0.x86_64-linux-gnu.tar.gz"
[[CSDP]]
arch = "powerpc64le"
git-tree-sha1 = "d70e58d6971d046b8c56fb2111fde9c24df248a7"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "8cacbda1a3f002786b454717e335ddceb7283fb852ad83de0d5d5f944d4911cb"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+6/CSDP.v6.2.0.powerpc64le-linux-gnu.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "46d05d0cbe02e3b1ae87e00c807b2726c8e14db3"
os = "macos"

    [[CSDP.download]]
    sha256 = "5d2f4de75b52bf2353e43f6e14125fa64dc1a90094c34bda552610088c128625"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+6/CSDP.v6.2.0.x86_64-apple-darwin14.tar.gz"
[[CSDP]]
arch = "aarch64"
git-tree-sha1 = "751320a59efab23e2fe97a8a87fc4305ebda8068"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "22254be98895d98b6d488effa1e8d6501b22c830cc8d509df1f51f84d577dece"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+6/CSDP.v6.2.0.aarch64-linux-gnu.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "9453e8beb6353278494b2f022f2ec5efedeaa315"
os = "freebsd"

    [[CSDP.download]]
    sha256 = "515cd2e0e95064467644d4157444efafe86ae308a17db00e29a01c5766408c27"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+6/CSDP.v6.2.0.x86_64-unknown-freebsd11.1.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "83dad073758fc1ec1cb3525e850a303cccbb6faf"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "e0651c1efd7fda7eab300e781840caccccb11f35499924390c3b33aad00dfa6a"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+6/CSDP.v6.2.0.x86_64-linux-musl.tar.gz"
