[[CSDP]]
arch = "i686"
git-tree-sha1 = "92e74a9a05581b00c3088bcaf9da891b43075fba"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "ae3c721dcb018d9aa8f8f32189abc7b48771d7b88dc2368fa0d97432eb1ed3b8"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+3/CSDP.v6.2.0.i686-linux-musl.tar.gz"
[[CSDP]]
arch = "aarch64"
git-tree-sha1 = "fd74841ea2ca24031fff7c55fe3ccdbbaceacea1"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "e46fcc72c34911ba6038096e85bad05a323211112298a26ce267fd0b4b6d5dbd"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+3/CSDP.v6.2.0.aarch64-linux-musl.tar.gz"
[[CSDP]]
arch = "i686"
git-tree-sha1 = "7410f71f02a01db1b9ed5a2a6ab556ba915d04c7"
os = "windows"

    [[CSDP.download]]
    sha256 = "6447fbf83e179e47e29aa52d7b72f8744460caa2f8c5774c2d73421c021209a3"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+3/CSDP.v6.2.0.i686-w64-mingw32.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "0edbc7767ed9e321b404e1c9a62cd6a544803756"
os = "windows"

    [[CSDP.download]]
    sha256 = "6da85dcd30fe35a6d6e08d44515d161c1a7db3c847efaf0deec65903d0ca5dc3"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+3/CSDP.v6.2.0.x86_64-w64-mingw32.tar.gz"
[[CSDP]]
arch = "armv7l"
git-tree-sha1 = "5624e751e2067d4366fe225185b592cae64b2632"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "97d88fcfea3241f97fa036153d24698355f4c7955d32650c0d023a53f55ce872"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+3/CSDP.v6.2.0.armv7l-linux-gnueabihf.tar.gz"
[[CSDP]]
arch = "armv7l"
git-tree-sha1 = "66853e27d53453d8966a57a5b6b30464e2dcced5"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "4f9e68c9cade67b212ef0e034cf3eaf52710150816714768f8277d475877f41d"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+3/CSDP.v6.2.0.armv7l-linux-musleabihf.tar.gz"
[[CSDP]]
arch = "i686"
git-tree-sha1 = "089f37805e45facd9a58160d5663fec2e7d2930d"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "73b0f297adcbc3ca16c930ccb2db8611bf68e6bb9f7e711be210aaa2b5400f95"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+3/CSDP.v6.2.0.i686-linux-gnu.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "ebf551cab93728f370e779c804d83c37388e0717"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "947aa5b90d68759c8c9d29e88e6d3d7b9851de338bbebddf8ad0cb8ed88245fd"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+3/CSDP.v6.2.0.x86_64-linux-gnu.tar.gz"
[[CSDP]]
arch = "powerpc64le"
git-tree-sha1 = "1d9649f70d0fe6b869496723349502d5276df479"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "e06c9aeed4b8cdac16da8095f6906fe60d1eb749c7f6a9df7b201ff3f1aca91f"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+3/CSDP.v6.2.0.powerpc64le-linux-gnu.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "b6a8481a62769e0fccf68616dc447672e24ff688"
os = "macos"

    [[CSDP.download]]
    sha256 = "c949f215eaaab09ddf6ccbd2dcdf04ea67069ac2941c949297a4a2bd2429d000"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+3/CSDP.v6.2.0.x86_64-apple-darwin14.tar.gz"
[[CSDP]]
arch = "aarch64"
git-tree-sha1 = "df3873e00c5dbc248b6dd77125c0a5e522682382"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "63bdc686f00c5899353b460d3e8a083368deb7aa2a6e3aac85beb7fc1c5b477a"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+3/CSDP.v6.2.0.aarch64-linux-gnu.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "ced4b1d29be78ddf389b6d66d23e17f2edd87e0b"
os = "freebsd"

    [[CSDP.download]]
    sha256 = "ad488d6f7fc3dd16e704a98e86d99d37553d2ab31a48b4bf5da2dc4f1ba5dab5"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+3/CSDP.v6.2.0.x86_64-unknown-freebsd11.1.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "4be2362cf95ea3dbaacb2f5bbfee076630ceaa7f"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "dccd19c117f881c8b4c1b25f93f15f4faf73cedea5ae11b74e709343acf11833"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+3/CSDP.v6.2.0.x86_64-linux-musl.tar.gz"
