[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "f87323214cb9b35278f2339db447e6895796d8a6"
os = "freebsd"

    [[CSDP.download]]
    sha256 = "13727fbc4d7d900825d079ed37fc810094d10a8663705bb58b6f21415bba361b"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+9/CSDP.v6.2.0.x86_64-unknown-freebsd11.1.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "04e257330de7a71c6222c29e9ececc6328dd0a42"
os = "windows"

    [[CSDP.download]]
    sha256 = "933c56d422941207e1c0d7409d6c5a6d0e27848638069b3f649a6c68ae568d3a"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+9/CSDP.v6.2.0.x86_64-w64-mingw32.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "47d7bfe98dd167dd4de23345db4cd7f07560e6e4"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "e6023806cea7c6872121dff3748b3ab630fde598594553c95e9058ef39af27d7"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+9/CSDP.v6.2.0.x86_64-linux-gnu.tar.gz"
[[CSDP]]
arch = "armv7l"
git-tree-sha1 = "0d23ce9b87c382cc0903896d6e7569c16cfc1175"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "24691e7738b0969049b19d1d440bb446af499c4716a543a50616a1b959333409"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+9/CSDP.v6.2.0.armv7l-linux-musleabihf.tar.gz"
[[CSDP]]
arch = "i686"
git-tree-sha1 = "81d5fcd5ec089429af1baa6194936dcbdc395b63"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "8edb678aeddb49a75d0aec913b4b44f1e2852ea19b84eff2dc104e8c4129175e"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+9/CSDP.v6.2.0.i686-linux-gnu.tar.gz"
[[CSDP]]
arch = "aarch64"
git-tree-sha1 = "53888665b40f8f96b00f0c07cf3cda835716cbd8"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "f2ae02ae8bf7a6901aa00bd4611823b61bff107cc850d53765b3e5635e20ee53"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+9/CSDP.v6.2.0.aarch64-linux-musl.tar.gz"
[[CSDP]]
arch = "i686"
git-tree-sha1 = "d2ff60a22fab53ae9d6372cc3ecad60868362419"
os = "windows"

    [[CSDP.download]]
    sha256 = "9f5c3d877b0fb8a5e70950d4986668fe25631d0075664e68ecb68063dbba39d2"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+9/CSDP.v6.2.0.i686-w64-mingw32.tar.gz"
[[CSDP]]
arch = "aarch64"
git-tree-sha1 = "353d99b76138e933df1583bc452550cea69a666a"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "61f4b8c4c2fcaa0ce8ccd5e7eb5b761e89b2e4dfe00b061a754e4f891cfa8780"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+9/CSDP.v6.2.0.aarch64-linux-gnu.tar.gz"
[[CSDP]]
arch = "i686"
git-tree-sha1 = "3e0818de984ef851d5bfc1d1874ae73de82420d1"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "7fdba3b19b840bab7fb36034067cc5d70c1cabf77b52e31e222a0d709111fadd"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+9/CSDP.v6.2.0.i686-linux-musl.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "c5f30da932191abea7a3cb037d0fb2b41c4a7476"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "c529996b46f3fc2ba0f4ab74091c16957ae65de765de119c001d4c5e29352ec3"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+9/CSDP.v6.2.0.x86_64-linux-musl.tar.gz"
[[CSDP]]
arch = "powerpc64le"
git-tree-sha1 = "2b3ecee9dbbb8a4285773143507e4da9666f704b"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "342010f07f08d20484a76577f1f429d52991f0901e8e873c846e01677deebc55"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+9/CSDP.v6.2.0.powerpc64le-linux-gnu.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "a80fb11726b12be839cf733ac8974ef58c39bc4a"
os = "macos"

    [[CSDP.download]]
    sha256 = "7fd94affc85edd41346851521601776d3b8164e0fb76f8d1644982be17800f0d"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+9/CSDP.v6.2.0.x86_64-apple-darwin14.tar.gz"
[[CSDP]]
arch = "armv7l"
git-tree-sha1 = "e6c238a5dcb003a0195921648876a08a5165acf9"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "183db7e7d3c2624d99f12b4494958ed5ff1cd555e407ea245a58e317d2a747bc"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+9/CSDP.v6.2.0.armv7l-linux-gnueabihf.tar.gz"
