[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "0ada4b7e311c1b36a6baafae365dfc9ffa972dcb"
os = "freebsd"

    [[CSDP.download]]
    sha256 = "fb5e85a76dcaae4e99f5aaf2502fdfb36172d11d222de6785c564aea0fe4f947"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+8/CSDP.v6.2.0.x86_64-unknown-freebsd11.1.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "e7d9a7e02562b37ab72a9fbf19623ec0b3ed0b0f"
os = "windows"

    [[CSDP.download]]
    sha256 = "f6ade4b6c2f5f515d6d89d687757c7adee85d55ef9e36ea35d7126e1af8f369a"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+8/CSDP.v6.2.0.x86_64-w64-mingw32.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "beaf0da6c4e86b2be7c1ef060864cee0739a9f9e"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "77adafad8d41d3e3e353b1e1544e697f4172b92e542e31d64c05f842c80ae5b0"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+8/CSDP.v6.2.0.x86_64-linux-gnu.tar.gz"
[[CSDP]]
arch = "armv7l"
git-tree-sha1 = "beda32b1b7d36e82e384d71c95702b4af5b6c628"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "2724a34c312e5a1be0c47365b290134039d16ce9633c7aab3bf278ddb91272b9"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+8/CSDP.v6.2.0.armv7l-linux-musleabihf.tar.gz"
[[CSDP]]
arch = "i686"
git-tree-sha1 = "44a175b2cb23228b642fa392945096ff05bdfc0b"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "10ddffb32b112cd6796d2aee733e72fae396ce38ff1fcbbe0bc833a00b524d1e"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+8/CSDP.v6.2.0.i686-linux-gnu.tar.gz"
[[CSDP]]
arch = "aarch64"
git-tree-sha1 = "3158bc6f9dba1b7fe66de9c5c0537a7c4b2f9c36"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "5111df8333bf1fa35fa8b18a3fd13a3354ddac59c2affa60434313af8a71b57d"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+8/CSDP.v6.2.0.aarch64-linux-musl.tar.gz"
[[CSDP]]
arch = "i686"
git-tree-sha1 = "36991c154eda43c76b87cafc4d2804bd44438661"
os = "windows"

    [[CSDP.download]]
    sha256 = "b7655c7f981f02f27871dfa222b4bc6b2852d39a0327998f62bce411d7b07066"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+8/CSDP.v6.2.0.i686-w64-mingw32.tar.gz"
[[CSDP]]
arch = "aarch64"
git-tree-sha1 = "08fa5c3e3b33b35d479dfa1edae7da1fbba46f99"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "27f0b509f41740729eb2df06b4819cdd26e8760338140ccab8eeda383a2a16ee"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+8/CSDP.v6.2.0.aarch64-linux-gnu.tar.gz"
[[CSDP]]
arch = "i686"
git-tree-sha1 = "9e2b342d229f751e604ba1c1a012733f7d0ecd78"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "c4163e28b259b0d7958b67c38d89aae9c495133d623f687ec153d251e653de94"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+8/CSDP.v6.2.0.i686-linux-musl.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "c26a15f4518c01e512e4368d9d76171745b1b293"
libc = "musl"
os = "linux"

    [[CSDP.download]]
    sha256 = "68a0867cc796843dda67ab887c2d3949cd13dfc67acf36d7a730cc9e19fb37ba"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+8/CSDP.v6.2.0.x86_64-linux-musl.tar.gz"
[[CSDP]]
arch = "powerpc64le"
git-tree-sha1 = "bd92210c0ad17b658a2e36f67c301e3505b57d10"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "6cc03ed5dd2cc1497374f80459977c86a72baa3791c3b20b5a9d3ce6e003b829"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+8/CSDP.v6.2.0.powerpc64le-linux-gnu.tar.gz"
[[CSDP]]
arch = "x86_64"
git-tree-sha1 = "991b8ac04e025220cc26194e7d6f263348a68797"
os = "macos"

    [[CSDP.download]]
    sha256 = "9934988a69a5b723370307dcfb550cd0e95622424afc7eff5c3f8f0afdd9e660"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+8/CSDP.v6.2.0.x86_64-apple-darwin14.tar.gz"
[[CSDP]]
arch = "armv7l"
git-tree-sha1 = "f90fc7ce73b9374bc2264b60d444caea5f2b1b39"
libc = "glibc"
os = "linux"

    [[CSDP.download]]
    sha256 = "e129881cde0dc6424f888d9a825d422e905114c7ffc57041d457740fead7ffc4"
    url = "https://github.com/JuliaBinaryWrappers/CSDP_jll.jl/releases/download/CSDP-v6.2.0+8/CSDP.v6.2.0.armv7l-linux-gnueabihf.tar.gz"
